title: "Proteïnes"
description: "Estudi de la seqüència, l'estructura i la funció de les proteïnes"
url: "https://biocomputing-teaching.github.io"
baseurl: ""
source: docs
destination: _site
timezone: Europe/Madrid
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
kramdown:
  input: GFM
  hard_wrap: false
relative_links:
  enabled: true
  collections: false
sass:
  style: compressed
defaults:
  - scope:
      path: ""
    values:
      layout: default
exclude:
  - .DS_Store
  - vendor
  - .bundle
  - QiEP/2024-2025/P1/Pràctica 1 Grup G/Pràctica 1. Grup G.html
  - QiEP/2024-2025/P1/Pràctica 1 Grup H/Pràctica QEB Grup H
  - QiEP/2024-2025/P1/Pràctica 1 Grup I/Practica1_JCI.html
  - QiEP/2024-2025/P1/Pràctica 1 Grup L/__MACOSX
  - QiEP/2024-2025/P1/Pràctica 1 Grup L/PRÀCTICA 1-2.html
