#theme: jekyll-theme-minimal
title: "Protin explorer"
remote-theme: benbalter/retlab 
website: https://biocomputing-teaching.github.io/Proteines
baseurl: /
permalink: date
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
actions/upload-artifact: v4
