#theme: jekyll-theme-minimal
title: "Protein explorer"
remote-theme: benbalter/retlab 
url: https://biocomputing-teaching.github.io/Proteines
permalink: date
baseurl: /Proteines
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
actions/upload-artifact: v4
